# Generated by Django 5.2.15 on 2026-07-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='organizations/logos/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('opportunity_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('job', 'Job'), ('fellowship', 'Fellowship'), ('exchange_program', 'Exchange Program'), ('competition', 'Competition'), ('training', 'Training')], max_length=32)),
                ('funding_type', models.CharField(choices=[('fully_funded', 'Fully Funded'), ('partially_funded', 'Partially Funded'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('free', 'Free'), ('other', 'Other')], max_length=32)),
                ('education_level', models.CharField(choices=[('bachelor', 'Bachelor'), ('masters', 'Masters'), ('phd', 'PhD'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('any', 'Any')], max_length=32)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('required_documents', models.TextField(blank=True)),
                ('application_process', models.TextField(blank=True)),
                ('official_link', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=180)),
                ('source_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='opportunities/images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.country')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='opportunities.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='opportunities', to='opportunities.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
